import { useState, useEffect, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';

export interface SupportTicket {
  id: string;
  ticket_number: string;
  tenant_id: string | null;
  user_id: string | null;
  subject: string;
  description: string | null;
  category: string;
  priority: string;
  status: string;
  assigned_to: string | null;
  resolved_at: string | null;
  resolved_by: string | null;
  created_at: string;
  updated_at: string;
  tenant_name?: string;
  assigned_admin_name?: string;
  assigned_admin_email?: string;
}

export interface TicketMessage {
  id: string;
  ticket_id: string;
  sender_id: string | null;
  sender_type: string;
  message: string;
  attachments: any;
  is_internal_note: boolean;
  created_at: string;
  sender_name?: string;
  sender_email?: string;
}

export function useSupportTickets() {
  const [tickets, setTickets] = useState<SupportTicket[]>([]);
  const [loading, setLoading] = useState(true);
  const { toast } = useToast();

  const fetchTickets = useCallback(async () => {
    try {
      setLoading(true);
      
      // Fetch tickets
      const { data: ticketData, error: ticketError } = await supabase
        .from('support_tickets')
        .select('*')
        .order('created_at', { ascending: false });

      if (ticketError) throw ticketError;

      // Fetch tenant names for tickets with tenant_id
      const tenantIds = [...new Set(ticketData?.filter(t => t.tenant_id).map(t => t.tenant_id) || [])];
      const { data: tenants } = await supabase
        .from('tenants')
        .select('id, name')
        .in('id', tenantIds.length > 0 ? tenantIds : ['']);

      // Fetch assigned admin profiles
      const adminIds = [...new Set(ticketData?.filter(t => t.assigned_to).map(t => t.assigned_to) || [])];
      const { data: admins } = await supabase
        .from('profiles')
        .select('id, full_name, email')
        .in('id', adminIds.length > 0 ? adminIds : ['']);

      // Map data
      const enrichedTickets: SupportTicket[] = (ticketData || []).map(ticket => ({
        ...ticket,
        tenant_name: tenants?.find(t => t.id === ticket.tenant_id)?.name,
        assigned_admin_name: admins?.find(a => a.id === ticket.assigned_to)?.full_name,
        assigned_admin_email: admins?.find(a => a.id === ticket.assigned_to)?.email,
      }));

      setTickets(enrichedTickets);
    } catch (err) {
      console.error('Error fetching tickets:', err);
      toast({
        title: 'Error',
        description: 'Failed to load support tickets',
        variant: 'destructive',
      });
    } finally {
      setLoading(false);
    }
  }, [toast]);

  const createTicket = async (ticketData: {
    tenant_id?: string;
    subject: string;
    description?: string;
    category?: string;
    priority?: string;
  }) => {
    try {
      const { data: userData } = await supabase.auth.getUser();
      
      const { data, error } = await supabase
        .from('support_tickets')
        .insert({
          ...ticketData,
          user_id: userData.user?.id,
          ticket_number: '', // Will be auto-generated by trigger
        })
        .select()
        .single();

      if (error) throw error;

      toast({
        title: 'Ticket Created',
        description: `Ticket ${data.ticket_number} has been created`,
      });

      await fetchTickets();
      return data;
    } catch (err) {
      console.error('Error creating ticket:', err);
      toast({
        title: 'Error',
        description: 'Failed to create ticket',
        variant: 'destructive',
      });
      return null;
    }
  };

  const updateTicket = async (ticketId: string, updates: Partial<SupportTicket>) => {
    try {
      const { error } = await supabase
        .from('support_tickets')
        .update(updates)
        .eq('id', ticketId);

      if (error) throw error;

      toast({
        title: 'Ticket Updated',
        description: 'The ticket has been updated',
      });

      await fetchTickets();
    } catch (err) {
      console.error('Error updating ticket:', err);
      toast({
        title: 'Error',
        description: 'Failed to update ticket',
        variant: 'destructive',
      });
    }
  };

  const assignTicket = async (ticketId: string, adminId: string) => {
    await updateTicket(ticketId, { 
      assigned_to: adminId,
      status: 'in_progress'
    });
  };

  const resolveTicket = async (ticketId: string) => {
    const { data: userData } = await supabase.auth.getUser();
    await updateTicket(ticketId, { 
      status: 'resolved',
      resolved_at: new Date().toISOString(),
      resolved_by: userData.user?.id
    });
  };

  useEffect(() => {
    fetchTickets();
  }, [fetchTickets]);

  return {
    tickets,
    loading,
    fetchTickets,
    createTicket,
    updateTicket,
    assignTicket,
    resolveTicket,
  };
}

export function useTicketMessages(ticketId: string | null) {
  const [messages, setMessages] = useState<TicketMessage[]>([]);
  const [loading, setLoading] = useState(false);
  const { toast } = useToast();

  const fetchMessages = useCallback(async () => {
    if (!ticketId) return;

    try {
      setLoading(true);
      
      const { data: messageData, error } = await supabase
        .from('support_ticket_messages')
        .select('*')
        .eq('ticket_id', ticketId)
        .order('created_at', { ascending: true });

      if (error) throw error;

      // Fetch sender profiles
      const senderIds = [...new Set(messageData?.filter(m => m.sender_id).map(m => m.sender_id) || [])];
      const { data: senders } = await supabase
        .from('profiles')
        .select('id, full_name, email')
        .in('id', senderIds.length > 0 ? senderIds : ['']);

      const enrichedMessages: TicketMessage[] = (messageData || []).map(msg => ({
        ...msg,
        sender_name: senders?.find(s => s.id === msg.sender_id)?.full_name,
        sender_email: senders?.find(s => s.id === msg.sender_id)?.email,
      }));

      setMessages(enrichedMessages);
    } catch (err) {
      console.error('Error fetching messages:', err);
    } finally {
      setLoading(false);
    }
  }, [ticketId]);

  const sendMessage = async (message: string, isInternalNote: boolean = false) => {
    if (!ticketId) return null;

    try {
      const { data: userData } = await supabase.auth.getUser();
      
      const { data, error } = await supabase
        .from('support_ticket_messages')
        .insert({
          ticket_id: ticketId,
          sender_id: userData.user?.id,
          sender_type: 'admin',
          message,
          is_internal_note: isInternalNote,
        })
        .select()
        .single();

      if (error) throw error;

      await fetchMessages();
      return data;
    } catch (err) {
      console.error('Error sending message:', err);
      toast({
        title: 'Error',
        description: 'Failed to send message',
        variant: 'destructive',
      });
      return null;
    }
  };

  useEffect(() => {
    fetchMessages();
  }, [fetchMessages]);

  return {
    messages,
    loading,
    fetchMessages,
    sendMessage,
  };
}
