// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdkrvztqeuflxilrtnws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNka3J2enRxZXVmbHhpbHJ0bndzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkwOTIyMjIsImV4cCI6MjA4NDY2ODIyMn0.Wzk1rWYrxGnhob0vfD-rC7kR50hWSThfuJ_6thUoDqA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});